book:
  appendices:
    - 100-instructors.qmd
    - 101-github.qmd     # only for html output
    - 102-rmarkdown.qmd  # only for html output
    - 103-tidyverse.qmd  # only for html output
    - 104-ggplot.qmd     # only for html output
