project:
  type: book
  preview:
    port: 4200

book:
  title: "Experimentology"
  subtitle: "An Open Science Approach to Experimental Psychology Methods"
  author:
    - "Michael C. Frank, Mika Braginsky, Julie Cachia,"
    - "Nicholas Coles, Tom E. Hardwicke, Robert Hawkins,"
    - "Maya Mathur, and Rondeline Williams"
  date: last-modified
  repo-url: https://github.com/langcog/experimentology
  repo-actions: [source, issue]
  downloads: [pdf]
  back-to-top-navigation: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - 001-experiments.qmd
        - 002-theories.qmd
        - 003-replication.qmd
        - 004-ethics.qmd
    - part: "Statistics"
      chapters:
        - 005-estimation.qmd
        - 006-inference.qmd
        - 007-models.qmd
    - part: "Planning"
      chapters:
        - 008-measurement.qmd
        - 009-design.qmd
        - 010-sampling.qmd
    - part: "Execution"
      chapters:
        - 011-prereg.qmd
        - 012-collection.qmd
        - 013-management.qmd
    - part: "Reporting"
      chapters:
        - 014-writing.qmd
        - 015-viz.qmd
        - 016-meta.qmd
        - 017-conclusions.qmd
  appendices:
    - 100-instructors.qmd
    - 100-appendices.qmd # only for latex output
    # - 101-github.qmd     # only for html output
    # - 102-rmarkdown.qmd  # only for html output
    # - 103-tidyverse.qmd  # only for html output
    # - 104-ggplot.qmd     # only for html output

# cap-location: margin       # figure and table captions in margin
reference-location: margin # footnotes in margin
link-citations: true       # citations link to references

bibliography: experimentology.bib
reference-section-title: References

df-print: kable
filters:
  - boxes

format:
  html:
    theme:
      light: [flatly, resources/global.scss]
      dark: [darkly, resources/global.scss]
    published-title: "Updated"

  pdf:
    documentclass: scrreprt
    classoption: bibliography=leveldown
    keep-tex: true
    citeproc: false # don't run pandoc default citation handling
    cite-method: biblatex
    biblatexoptions: style=authoryear, refsection=chapter
    include-in-header: tex/preamble.tex
    toc-depth: 1 # level 1 headings (i.e. parts and chapters)
    toc-title: Contents # title of table of contents
    # links-as-notes: true # turn URLs into sidenotes
    mainfont: ETbb # tufte font
    sansfont: Source Sans Pro
    citecolor: DarkGreen # tufte color
    linkcolor: DarkBlue # tufte color
    urlcolor: DarkGreen # tufte color

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    cache.lazy: FALSE
    dev: "png"
    dpi: 300

execute: 
  echo: false
  message: false
  warning: false
  error: false
  cache: true
  code-overflow: wrap
  tidy: true
