project:
  type: book
  preview:
    port: 4200

book:
  title: "Experimentology"
  subtitle: "An Open Science Approach to Experimental Psychology Methods"
  author:
    - "Michael C. Frank, Mika Braginsky, Julie Cachia,"
    - "Nicholas Coles, Tom E. Hardwicke, Robert Hawkins,"
    - "Maya Mathur, and Rondeline Williams"
  date: last-modified
  repo-url: https://github.com/langcog/experimentology
  repo-actions: [source, issue]
  downloads: [pdf]
  back-to-top-navigation: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters: 
        - 001-experiments.qmd
        - 002-theories.qmd
        - 003-replication.qmd
        - 004-ethics.qmd
    - part: "Statistics"
      chapters:
        - 005-estimation.qmd
        - 006-inference.qmd
        - 007-models.qmd
    - part: "Planning"
      chapters:
        - 008-measurement.qmd
        - 009-design.qmd
        - 010-sampling.qmd
    - part: "Execution"
      chapters:
        - 011-prereg.qmd
        - 012-collection.qmd
        - 013-management.qmd
    - part: "Reporting"
      chapters:
        - 014-writing.qmd
        - 015-viz.qmd
        - 016-meta.qmd
        - 017-conclusions.qmd
  appendices:
    - 100-instructors.qmd
    - 101-github.qmd
    - 102-rmarkdown.qmd
    - 103-tidyverse.qmd
    - 104-ggplot.qmd

published-title: "Updated"

bibliography: experimentology.bib
reference-section-title: References

format:
  html:
    theme:
      light: [flatly, resources/global.scss]
      dark: [darkly, resources/global.scss]
  pdf:
    documentclass: scrreprt
    # classoption:
    #   - paper=6in:10in
      # - DIV=calc
    keep-tex: true
    include-in-header: preamble.tex
    toc-depth: 1
    # geometry:
    #   - paperheight=10in
    #   - paperwidth=6in
      # - margin=.75in
    fontfamily: ETbb
    sansfont: Source Sans Pro

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    cache.lazy: FALSE
    dev: "png"
    dpi: 300
    cap-location: margin

execute: 
  echo: false
  message: false
  warning: false
  error: false
  cache: true

reference-location: margin
